name: build

on:
  release:
    types: [released]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/publish.yml@9f1fedda61294df4c004c05519a3fbf3b8e1f32f # v2.3.1
    with:
      env: |
        FFTW_DIR: /opt/homebrew/opt/fftw/lib/
      targets: |
        # Linux wheels
        - cp3*-manylinux_x86_64
        # MacOS wheels
        - cp3*-macosx_x86_64
        # MacOS arm64 wheels
        - cp3*-macosx_arm64
      sdist: true
      test_command: python -c "from romanisim import ramp_fit_casertano"
      upload_to_pypi: ${{ (github.event_name == 'release') && (github.event.action == 'released') }}
    secrets:
      pypi_token: ${{ secrets.PYPI_PASSWORD_STSCI_MAINTAINER }}
