name: extra tests

on:
  schedule:
    # Weekly Monday 6AM build
    - cron: "0 0 * * 1"
  pull_request:
    # We also want this workflow triggered if the `Weekly CI` label is
    # added or present when PR is updated
    types:
      - synchronize
      - labeled
  workflow_dispatch:
    inputs:
      crds_context:
        description: CRDS context (leave blank for latest)
        type: string
        required: false
        default: ""
      crds_server:
        description: CRDS server
        type: string
        required: false
        default: https://roman-crds.stsci.edu

jobs:
  latest_crds_contexts:
    if: (github.repository == 'spacetelescope/romancal' && (github.event_name == 'schedule' || github.event_name == 'push' || github.event_name == 'workflow_dispatch' || contains(github.event.pull_request.labels.*.name, 'run extra tests')))
    uses: spacetelescope/crds/.github/workflows/contexts.yml@main
    with:
      observatory: roman
  crds_context:
    if: (github.repository == 'spacetelescope/romancal' && (github.event_name == 'schedule' || github.event_name == 'push' || github.event_name == 'workflow_dispatch' || contains(github.event.pull_request.labels.*.name, 'run extra tests')))
    needs: [latest_crds_contexts]
    runs-on: ubuntu-latest
    steps:
      - id: context
        run: echo context=${{ github.event_name == 'workflow_dispatch' && (inputs.crds_context != '' && inputs.crds_context || needs.latest_crds_contexts.outputs.roman) || needs.latest_crds_contexts.outputs.roman }} >> $GITHUB_OUTPUT
    outputs:
      context: ${{ steps.context.outputs.context }}
  latest_data_cache:
    if: (github.repository == 'spacetelescope/romanisim' && (github.event_name == 'schedule' || github.event_name == 'push' || github.event_name == 'workflow_dispatch' || contains(github.event.pull_request.labels.*.name, 'run extra tests')))
    uses: ./.github/workflows/retrieve_cache.yml
    with:
      cache_path: /tmp/data
  test:
    if: (github.repository == 'spacetelescope/romanisim' && (github.event_name == 'schedule' || github.event_name == 'push' || github.event_name == 'workflow_dispatch' || contains(github.event.pull_request.labels.*.name, 'run extra tests')))
    needs: [crds_context, latest_data_cache]
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@99401c364fa51c9c507d3cd6d272049278ac0b2c # v2.4.0
    with:
      libraries: |
        apt:
          - libxml2-dev
          - libxslt1-dev
        brew:
          - eigen
          - fftw
      setenv: |
        CRDS_PATH: /tmp/data/crds_cache/
        CRDS_SERVER_URL: ${{ github.event_name == 'workflow_dispatch' && inputs.crds_server || 'https://roman-crds.stsci.edu' }}
        CRDS_CONTEXT: ${{ needs.crds_context.outputs.context }}
        CRDS_CLIENT_RETRY_COUNT: 3
        CRDS_CLIENT_RETRY_DELAY_SECONDS: 20
        STPSF_PATH: ${{ needs.latest_data_cache.outputs.cache_path }}/stpsf-data/
        GALSIM_CAT_PATH: ${{ needs.latest_data_cache.outputs.cache_path }}/galsim_data/real_galaxy_catalog_23.5_example.fits
        FFTW_DIR: /opt/homebrew/opt/fftw/lib/
      cache-path: ${{ needs.latest_data_cache.outputs.cache_path }}
      cache-restore-keys: |
        ${{ needs.latest_data_cache.outputs.cache_key }}
      cache-key: crds-${{ needs.crds_context.outputs.context }}-${{ needs.latest_data_cache.outputs.cache_key }}
      envs: |
        - macos: py311
        - macos: py312
        - macos: py313
        - macos: py313-devdeps
        - linux: py313-devdeps
