name: tests

on:
  push:
    branches:
      - main
      - "*.x"
    tags:
      - "*"
  pull_request:
    branches:
      - main
  schedule:
    # Weekly Monday 9AM build
    # * is a special character in YAML so you have to quote this string
    - cron: "0 9 * * 0"
  workflow_dispatch:
    inputs:
      crds_context:
        description: CRDS context (leave blank for latest)
        type: string
        required: false
        default: ""
      crds_server:
        description: CRDS server
        type: string
        required: false
        default: https://roman-crds.stsci.edu

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ inputs.crds_context }}
  cancel-in-progress: true

jobs:
  check:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@99401c364fa51c9c507d3cd6d272049278ac0b2c # v2.4.0
    with:
      envs: |
        - linux: check-style
  latest_crds_contexts:
    uses: spacetelescope/crds/.github/workflows/contexts.yml@main
    with:
      observatory: roman
  crds_context:
    needs: [latest_crds_contexts]
    runs-on: ubuntu-latest
    steps:
      - id: context
        run: echo context=${{ github.event_name == 'workflow_dispatch' && (inputs.crds_context != '' && inputs.crds_context || needs.latest_crds_contexts.outputs.roman) || needs.latest_crds_contexts.outputs.roman }} >> $GITHUB_OUTPUT
    outputs:
      context: ${{ steps.context.outputs.context }}
  latest_data_cache:
    uses: ./.github/workflows/retrieve_cache.yml
    with:
      cache_path: /tmp/data
  test:
    needs: [crds_context, latest_data_cache]
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@99401c364fa51c9c507d3cd6d272049278ac0b2c # v2.4.0
    with:
      libraries: |
        apt:
          - libxml2-dev
          - libxslt1-dev
        brew:
          - eigen
          - fftw
      setenv: |
        CRDS_PATH: /tmp/data/crds_cache/
        CRDS_SERVER_URL: ${{ github.event_name == 'workflow_dispatch' && inputs.crds_server || 'https://roman-crds.stsci.edu' }}
        CRDS_CONTEXT: ${{ needs.crds_context.outputs.context }}
        CRDS_CLIENT_RETRY_COUNT: 3
        CRDS_CLIENT_RETRY_DELAY_SECONDS: 20
        STPSF_PATH: ${{ needs.latest_data_cache.outputs.cache_path }}/stpsf-data/
        GALSIM_CAT_PATH: ${{ needs.latest_data_cache.outputs.cache_path }}/galsim_data/real_galaxy_catalog_23.5_example.fits
        FFTW_DIR: /opt/homebrew/opt/fftw/lib/
      cache-path: ${{ needs.latest_data_cache.outputs.cache_path }}
      cache-restore-keys: |
        ${{ needs.latest_data_cache.outputs.cache_key }}
      cache-key: crds-${{ needs.crds_context.outputs.context }}-${{ needs.latest_data_cache.outputs.cache_key }}
      envs: |
        - linux: py311-oldestdeps-cov
        - linux: py311
        - linux: py312
        - linux: py313
        # `tox` does not currently respect `requires-python` versions when creating testing environments;
        # if this breaks, add an upper pin to `requires-python` and revert this py3 to the latest working version
        - linux: py313-cov
          coverage: codecov
        - macos: py313
  test_downstream:
    needs: [crds_context, latest_data_cache]
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@9f1fedda61294df4c004c05519a3fbf3b8e1f32f  # v2.3.1
    with:
      setenv: |
        CRDS_PATH: ${{ needs.environment.outputs.data_path }}/crds
        CRDS_SERVER_URL: https://roman-crds.stsci.edu
        CRDS_CLIENT_RETRY_COUNT: 3
        CRDS_CLIENT_RETRY_DELAY_SECONDS: 20
      cache-path: ${{ needs.environment.outputs.data_path }}/crds
      cache-key: crds-${{ needs.crds_contexts.outputs.roman }}
      envs: |
        - linux: py313-romancal

